### ISSUE TITLE
Routing parameters

### ISSUE THREAD

**Issue by Wonderbox2000** [tammon/docker-compose-kylemanna-openvpn#1]
Hi,

First of all, thank you for this image and all the technical details coming with it !

I am using the image with docker-compse and the connected clients are able to access the distant network ressources.

My question : what parameters should I add to my docker-compse.yml to give access to internet to all my clients ?
I think I need to have routing parameters gateway, dns etc.

```
version: '2'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
#    ports:
#     - "1194:1194/udp"
    restart: unless-stopped
    volumes:
     - ./openvpn-data/conf:/etc/openvpn
    network_mode: host
```
